### ISSUE TITLE
Can't launch examples on Windows 10 with MSVC 2017 (2019) x64

### ISSUE THREAD

**Issue by KerimMatlab** [ChrisDrozdowski/h5cpp-windows#3]
Hi,

I have built HDF5 1.10.6 library that works. I also have ZLIB and Armadillo and now I'm trying to lauch examples from h5cpp.
I downloaded Chris Drozdowski h5cpp distribution that as far as I know doesn't have to be built (just download and run).
When I try to launch **attribute** example or **basics** example and neither of them works. When I compile them I get an error:

- **C:\apps\h5cpp_windows\h5cpp\H5Dwrite.hpp:60: error: C2666: ‘h5::write’: 2 overloads have similar conversions**
- could be 'h5::ds_t h5::write<T,const h5::dxpl_t&,const T*&>(const std::string &,const std::string &,T &&,const h5::dxpl_t &,const T *&)' with [T=element_t]
- or       'h5::ds_t h5::write<T,const h5::dxpl_t&,const T*&>(const h5::fd_t &,const std::string &,const T &,const h5::dxpl_t &,const T *&)' with [T=element_t]
- or       'h5::ds_t h5::write<T,const h5::dxpl_t&,const T*&>(const h5::fd_t &,const std::string &,const T *,const h5::dxpl_t &,const T *&)' with [T=element_t]
- or       'h5::impl::detail::hid_t<T,herr_t H5Dclose(hid_t),true,true,4> h5::write<__int64,h5::sp_t&,const h5::dxpl_t&,const __int64*&>(const h5::ds_t &,const __int64 &,h5::sp_t &,const h5::dxpl_t &,const __int64 *&)' with [T=h5::impl::ds_t]
- or       'h5::ds_t h5::write<T,h5::sp_t&,const h5::dxpl_t&,const T*&>(const h5::ds_t &,const T *,h5::sp_t &,const h5::dxpl_t &,const T *&)' with [T=element_t]
- or       'void h5::write<T>(const h5::ds_t &,const h5::sp_t &,const h5::sp_t &,const h5::dxpl_t &,const T *)' with [T=element_t]
- while trying to match the argument list '(const h5::ds_t, h5::sp_t, h5::sp_t, const h5::dxpl_t, const T *)' with [T=element_t]
- qualification adjustment (const/volatile) may be causing the ambiguity
- see reference to function template instantiation 'h5::ds_t h5::write<element_t,const h5::count_t&>(const h5::ds_t &,const T *,const h5::count_t &)' being compiled with [T=element_t]
- see reference to function template instantiation 'h5::impl::detail::hid_t<T,herr_t H5Dclose(hid_t),true,true,4> h5::write<arma::Mat<arma::s64>,>(const h5::ds_t &,const arma::Mat<arma::s64> &)' being compiled with [T=h5::impl::ds_t]
- see reference to function template instantiation 'h5::ds_t h5::write<arma::imat,>(const h5::fd_t &,const std::string &,const T &)' being compiled with [T=arma::imat]

As I see it is a single error with explanation to it (I removed path **C:\apps\h5cpp_windows\h5cpp\H5Dwrite.hpp** from all lines except the first one).

I work in Qt 5.14.0 with MSVC 2017 (2019) x64 so I add libraries in my QMake -.pro file with commands:
`LIBS += C:\apps\MSVC_apps_debug\HDF5_1106\lib\libhdf5_D.lib \`
`        C:\apps\MSVC_apps_debug\HDF5_1106\lib\libhdf5_hl_D.lib \`
`        C:\apps\MSVC_apps_debug\ZLIB\lib\libzlib_D.lib`
`INCLUDEPATH += C:\apps\MSVC_apps_debug\HDF5_1106\include \`
`               C:\apps\MSVC_apps_debug\ZLIB\include \`
`               C:\apps\MSVC_apps_debug\armadillo-9.800.3\include \`
`               C:\apps\h5cpp_windows`
`DEPENDPATH += C:\apps\MSVC_apps_debug\HDF5_1106\include \`
`              C:\apps\MSVC_apps_debug\ZLIB\include \`
`              C:\apps\MSVC_apps_debug\armadillo-9.800.3\include`
`              C:\apps\h5cpp_windows`

Kerim

**Comment by ChrisDrozdowski** [comment]
Can you start by building the examples solution using VS 2017 without any QT- just pure VS? I don't have QT installed and don't have the time now to get to know QT.

Note that the examples already have Armadillo and Eigen3 source code included. Also HDF5 1.10.6 is assumed to be in `C:\Program Files\HDF_Group\HDF5\1.10.6` per the prebuilt `hdf5-1.10.6-Std-win10_64-vs15` binary installer.

I am able to successfully build and run them them with Visual Studio 15.9.12 without issue except for many warnings (no errors).

**Comment by KerimMatlab** [comment]
Chris,
I'm trying to run exaples from Visual Studio 2017. I don't have experience of working in it but I know that I have to add libraries and include directories to these libraries.
Lets suppose I work in Debug mode.
**I add include folders as:**
Right click on project -> Properties -> Configuration Properties -> C/C++ -> General -> Additional Include Directories. Here I have 5 lines:

- $(SolutionDir)../
- C:\apps\MSVC_apps_debug\armadillo-9.800.3\include
- C:\apps\MSVC_apps_debug\HDF5_1106\include
- C:\apps\MSVC_apps_debug\ZLIB\include
- C:\apps\h5cpp_windows\h5cpp

**I add static libraries as:**
Right click on project -> Properties -> Configuration Properties -> Linker -> Input. Here I have 2 lines:
- C:\apps\MSVC_apps_debug\HDF5_1106\lib\libhdf5_D.lib
- C:\apps\MSVC_apps_debug\ZLIB\lib\libzlib_D.lib

If I run build then I get many errors connected with linking h5cpp like:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_H5open referenced in function "struct h5::impl::detail::hid_t<struct h5::impl::ds_t,&int __cdecl H5Dclose(__int64),1,1,4> __cdecl h5::create<short,struct h5::impl::array<struct h5::impl::current_dims_t,7>,struct h5::impl::array<struct h5::impl::max_dims_t,7>,struct h5::impl::detail::hid_t<struct h5::impl::dcpl_t,&int __cdecl H5Pclose(__int64),1,1,1> &>(struct h5::impl::detail::hid_t<struct h5::impl::fd_t,&int __cdecl H5Fclose(__int64),1,1,0> const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct h5::impl::array<struct h5::impl::current_dims_t,7> &&,struct h5::impl::array<struct h5::impl::max_dims_t,7> &&,struct h5::impl::detail::hid_t<struct h5::impl::dcpl_t,&int __cdecl H5Pclose(__int64),1,1,1> &)" (??$create@FU?$array@Ucurrent_dims_t@impl@h5@@$06@impl@h5@@U?$array@Umax_dims_t@impl@h5@@$06@23@AEAU?$hid_t@Udcpl_t@impl@h5@@$1?H5Pclose@@YAH_J@Z$00$00$00@detail@23@@h5@@YA?AU?$hid_t@Uds_t@impl@h5@@$1?H5Dclose@@YAH_J@Z$00$00$03@detail@impl@0@AEBU?$hid_t@Ufd_t@impl@h5@@$1?H5Fclose@@YAH_J@Z$00$00$0A@@230@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$$QEAU?$array@Ucurrent_dims_t@impl@h5@@$06@30@$$QEAU?$array@Umax_dims_t@impl@h5@@$06@30@AEAU?$hid_t@Udcpl_t@impl@h5@@$1?H5Pclose@@YAH_J@Z$00$00$00@230@@Z)	basics	C:\apps\h5cpp_windows\examples\examples\basics\basics.obj	1	
`
Here I have C++17 enabled

When I first time opened `Right click on project -> Properties -> Configuration Properties -> Linker -> Input -> Additinal Dependencies` I had this list of libraries:
- blas_win64_MT.lib
- lapack_win64_MT.lib
- zlib.lib
- hdf5.lib
- kernel32.lib
- user32.lib
- gdi32.lib
- winspool.lib
- comdlg32.lib
- advapi32.lib
- shell32.lib
- ole32.lib
- oleaut32.lib
- uuid.lib
- odbc32.lib
- odbccp32.lib

Since I don't know where are those libraries I just deleted all of them and wrote my libraries:
- C:\apps\MSVC_apps_debug\HDF5_1106\lib\libhdf5_D.lib
- C:\apps\MSVC_apps_debug\ZLIB\lib\libzlib_D.lib

If I don't do that then Linker couldn't find blas_win64_MT.lib
On the picture you can see my included libraries:
![libs](https://user-images.githubusercontent.com/43808863/73939538-be4d9200-48fa-11ea-84d9-c037ee3385bd.png)




I'm sorry but I don't want to use precompiled `hdf5-1.10.6-Std-win10_64-vs15` library because I need to configure this libraries for my needs. And I did it and my HDF5 library works.

**Comment by ChrisDrozdowski** [comment]
Did you compile HDF5 and zlib as DLLs and want to use the DLLs?

**Comment by KerimMatlab** [comment]
I have both: static and dynamic libraries of HDF5 and ZLIB. Prefix "libhdf5.lib" (first three letters in the name of library) means that this is static library (HDF5 documentation says that). "hdf5.lib" is a dynamic library. All of this also refer to ZLIB.

So I have `#define H5_BUILT_AS_DYNAMIC_LIB` and now I tried to link dynamic HDF5 and ZLIB libraries. To do this I simply wrote to `Right click on project -> Properties -> Configuration Properties -> Linker -> Input -> Additinal Dependencies` paths to the hdf5_D.lib and zlib_D.lib. Now it looks like:
- C:\apps\MSVC_apps_debug\HDF5_1106\lib\hdf5_D.lib
- C:\apps\MSVC_apps_debug\ZLIB\lib\zlib_D.lib
I also copied .dll files to the project folder

Now the application is compiled with errors and I can see the output in Console:
`int`
`data type: int value valid`
`THIS ERROR is on PURPOSE: c:\apps\h5cpp_windows\h5cpp\h5pall.hpp line#  68 : failed to parse arguments...`

`C:\apps\h5cpp_windows\examples\x64\Debug\basics.exe (process 7748) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.`
`Press any key to close this window . . .`

Here is print screen:
![VS_error](https://user-images.githubusercontent.com/43808863/73956664-53aa4f80-4916-11ea-9635-c83cc75b169f.png)

**Comment by ChrisDrozdowski** [comment]
That is the expected output for the basics example so that means you are now getting successful compilation. Good.

PDB files contain debugging information for their respective library. They don't seems to ship with Visual Studio. VS will attempt to download them but may not get around to it. It is perfectly fine if they are not found unless you want to debug those modules. I get the same output regarding PDB files.

The rest is now a matter of using the examples and the docs (http://sandbox.h5cpp.org/architecture/#hdf5) to learn how h5cpp works. I may not always have the answers from now on but you can ask Steven Varga the original author (https://github.com/steven-varga/h5cpp).

**Comment by KerimMatlab** [comment]
Yes, it works
I can see .h5 files created by this examples.
Thank you!
Now I need to figure out why it doesn't work in Qt. If I find the solution I will notice you
